sudo: required
services:
  - docker

before_install:
  - docker build -t jukeaban/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jukeaban/react-test npm test

after_success:
  - docker build -t jukeaban/react-complex-client ./client
  - docker build -t jukeaban/react-complex-nginx ./nginx
  - docker build -t jukeaban/react-complex-server ./server
  - docker build -t jukeaban/react-complex-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jukeaban/react-complex-client
  - docker push jukeaban/react-complex-nginx
  - docker push jukeaban/react-complex-server
  - docker push jukeaban/react-complex-worker
#  Take these images and push them to docker hub

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-docker-complex
  env: MultiDockerComplex-env
#  Go to S3 to get this
  bucket_name: elasticbeanstalk-us-west-1-735365176421
  bucker_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY



