version: '3'
services: 
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  api:
    depends_on:
      - postgres
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      # Tells our app to leave this folder as is
      - /app/node_modules
      # Tells docker to look at the server directory and 
      # copy everything inside of there, into our app directory inside of the container
      # Any time our app tries to access anything inside of the app directory
      # inside of the container
      # Except for the node_modules folder, it will essentially get redirected 
      # Back to the server directory inside of the currect project folder
      
      # This makes it so that any time we make a change to our source code
      # Docker will automatically rebuild
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_POST=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    environment:
      - REDIS_HOST=redis
      - REDIS_POST=6379
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
      